project:
  type: website
  output-dir: docs

website:
  title: "ENTMLGY 6703 - Jelmer's lectures"
  site-url: https://jelmerp.github.io/ENTMLGY6703
  repo-url: https://github.com/jelmerp/ENTMLGY6703
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    left:
      - href: index.qmd
        icon: house
        text: " "
      - text: "Week 3: HTS"
        menu: 
          - text: "Lecture: High-throughput Sequencing & Genomes"
            href: lectures/sequencing.qmd
          - text: "Lab part 1: Computational Infrastructure"
            href: labs/infrastructure.qmd
          - text: "Lab part 2: Working with genome and HTS Data"
            href: labs/data.qmd
      - text: "Week 4: RNA-seq"
        menu: 
          - text: "Lecture: RNA-seq"
          - text: "Lab: Differential expression analysis"
    right:
      - text: Other Pages
        menu: 
          - text: "R Homework"
            href: r_homework.qmd
          - text: "Overview of common Unix shell commands"
      - text: About
        href: about.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/jelmerp/ENTMLGY6703
          - text: Report an Issue
            url:  https://github.com/jelmerp/ENTMLGY6703/issues/new
format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    number-sections: true
    grid:
      body-width: 900px

editor: visual

